services:
  bot:
    build: .
    container_name: api_monitor_bot
    restart: always
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - api_monitor_bot_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${METRICS_PORT:-8080}/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

volumes:
  api_monitor_bot_data:


