# docker-compose.yml
# Файл для оркестрації (запуску) наших контейнерів

services:
  bot:
    build: .
    container_name: api_monitor_bot
    restart: always
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; print('ok')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s